### ISSUE TITLE
Demo support?

### ISSUE THREAD

**Issue by neuromancer** [kromenak/gengine#10]
Hi,

I was wondering if you plan to support [the GK3 demo](http://www.sierrachest.com/index.php?a=games&id=39&fld=demos), which could be useful for people to play some part of the game using this engine, without the need to buy it.

**Comment by kromenak** [comment]
Hi, sorry for the (very) delayed response - I'm not opposed to supporting the demo, but it wouldn't be a high priority right now. I will leave this ticket open for the time being though.

**Comment by neuromancer** [comment]
Thanks for the response. Is it a large effort to add it or do you think someone else could do it?

**Comment by kromenak** [comment]
The effort required depends on how similar the demo's data files are to the final game's data files. Between release of the demo and the final game, it's possible for a lot of things to change - data file formats change, the way the code interprets the data files can change, etc. If the demo data files are very different from the final game's data files, then it would be more complex to get those data files to work.

Since the engine code is open source, theoretically anyone who'd like could attempt to run the engine against the demo data files.

**Comment by mondegreengames** [comment]
I tried it. It works pretty well. Things I had to change:

* Changed the hard-coded barn list in GEngine.cpp to just "Gk3demo.brn"
* Changed the hard-coded timeblock start and location in GEngine.cpp to "212P" and "CSE"
* Added `if(actor.model != nullptr)` around line 572 in SceneInitFile.cpp to avoid a crash. `actor.model` can be null, since the SIF includes a reference to Gabe, but his model asset isn't included in the demo, so it's null.

Some other random things I noticed when playing through the demo:

* There's a splash screen that pops up at the very beginning. That works, but it says "click anywhere", but when you do it shows the verb chooser. Once you pick a verb the splash screen goes away and you can continue.
* The laser scene in the library doesn't really work (not surprising, since I think that was a bunch of special-case code in the actual GK3 engine)
* The point total is wrong. It shows all 965 points as available
* Debug output reports missing Sheep exports, mostly `SetCameraAngleType` and `FinishedScreen`

**Comment by kromenak** [comment]
@mondegreengames, thanks for looking into this! Since it isn't too tricky to get it working, I may be able to review and roll in these changes before the next release.

One thought is to detect the presence of "Gk3demo.brn", and if it exists, load the engine in "demo mode," utilizing some of the changes you've outlined above. Otherwise, it loads in "full game mode."

I actually haven't reviewed/investigated the laser puzzle scene at all yet, so not too surprising it's busted!

**Comment by kromenak** [comment]
Support for Demo mode has been added in the latest release (v0.0.8).

To enable the demo, simply put "Gk3demo.brn" in the Data folder. When the game detects this file, it will start the game in "demo mode," where you should be able to play the full demo.
