### ISSUE TITLE
broken links on clarkkromenaker

### ISSUE THREAD

**Issue by jamieS95** [kromenak/gengine#4]
specific commit links broken in:
http://clarkkromenaker.com/post/gengine-04-rendering/ 

could you also add some up to date tutorials for making a simple game

**Comment by kromenak** [comment]
Hi, I reviewed the article and fixed any broken links. In particular, a link to the commit for rendering here was pointing to an old Bitbucket URL. Since I moved the repo to GitHub, I updated that link.

As for tutorials, I'm trying to do tutorials as time permits - glad to know that there is some interest!

Let me know if you see any other problems!
